# Generated by Django 5.1.4 on 2025-01-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0002_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demanda',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=20),
        ),
    ]
